function dy = shapef(u,y,para,ka,la,ksig,mu,mub,Ga2,Sig0,xi,Di,sigeq0,sigeqM,Sp,sp,Vext,a,b,Vr)

fn0 = para(2);
v0 = para(3);
dy = zeros(12,1);     % a column vector
p = y(1,:);            % tangential angle psi
dp = y(2,:);           % derivative psi'
r = y(3,:);            % shape variable r
z = y(4,:);            % shape variable z
al = y(5,:);           % lagrangian multiplier alpha 
be = y(6,:);           % lagrangian multiplier beta
vu = y(7,:);           % tangential velocity vu
dvu = y(8,:);          % the derivative of vu'
sig = y(9,:);          % motor concentration sigma
dsig = y(10,:);        % the derivatvie of sigma'
vol = y(11);           % the volume of the cell
h = y(12,:);           % h = sqrt(r'^2 + z'^2);

%%%%%%%%%%%%Constraint Shell%%%%%%%%%%%%
dd = z.^2./a.^2+r.^2./b.^2-1;
fr = -2.*r.*sp.*Vext.*exp(sp.*dd)./b.^2;
rmin = 0.01*3;
fr = fr + Vr*(1./(r-rmin).^2-1./(0.1-rmin).^2).*(r<0.1).*(u>0.05).*(u<0.95);
fz = -2.*z.*sp.*Vext.*exp(sp.*dd)./a.^2;
fn = fn0 + fz.*cos(p)+fr.*sin(p);
fu = 0;
Ga1 = 0;
% Here we define the form of the regulation function
dka = 0;
sigeq = sigeq0 + (sigeqM-sigeq0)*exp(-Sp*(u-1/2).^2);
c0 = 0;

dy(1,:)=dp;

dy(2,:)=(-1).*dka.*dp.*ka.^(-1)+ c0.*dka.*h.*ka.^(-1)+ (-1).*dp.*h.*r.^(-1) ...
  .*cos(p)+ be.*h.^2.*ka.^(-1).*r.^(-1).*cos(p)+ (-1).*dka.*h.*ka.^( ...
  -1).*r.^(-1).*sin(p)+ al.*h.^2.*ka.^(-1).*r.^(-1).*sin(p)+ h.^2.* ...
  r.^(-2).*cos(p).*sin(p);

dy(3,:)=h.*cos(p);

dy(4,:)=(-1).*h.*sin(p);

dy(5,:)=(-1).*c0.*dp.*ka+ (1/2).*dp.^2.*h.^(-1).*ka+ (1/2).*c0.^2.*h.*ka+ ( ...
  -1).*fn.*h.*r.*sin(p)+ dp.*la.*r.*sin(p)+ 2.*dp.*dvu.*h.^(-1).*mu.* ...
  r.*sin(p)+ 2.*dp.*dvu.*h.^(-1).*mub.*r.*sin(p)+ dp.*r.*sig.^2.*( ...
  sig.^2+ Sig0.^2).^(-1).*xi.*sin(p)+ Ga1.*h.*r.*v0.*cos(p).*sin(p)+  ...
  2.*dp.^2.*h.^(-1).*mu.*r.*v0.*cos(p).*sin(p)+ 2.*dp.^2.*h.^(-1).* ...
  mub.*r.*v0.*cos(p).*sin(p)+ h.*la.*sin(p).^2+ 2.*dvu.*mub.*sin(p) ...
  .^2+ (-1/2).*h.*ka.*r.^(-2).*sin(p).^2+ h.*sig.^2.*(sig.^2+ Sig0.^2) ...
  .^(-1).*xi.*sin(p).^2+ dp.*mub.*vu.*sin(2.*p)+ 2.*dp.*mub.*v0.*sin( ...
  p).*sin(2.*p)+ h.*mu.*r.^(-1).*vu.*sin(p).*sin(2.*p)+ h.*mub.*r.^( ...
  -1).*vu.*sin(p).*sin(2.*p)+ h.*mu.*r.^(-1).*v0.*sin(p).^2.*sin(2.* ...
  p)+ h.*mub.*r.^(-1).*v0.*sin(p).^2.*sin(2.*p);

dy(6,:)=(-1).*fn.*h.*r.*cos(p)+ dp.*la.*r.*cos(p)+ 2.*dp.*dvu.*h.^(-1).* ...
  mu.*r.*cos(p)+ 2.*dp.*dvu.*h.^(-1).*mub.*r.*cos(p)+ dp.*r.*sig.^2.*( ...
  sig.^2+ Sig0.^2).^(-1).*xi.*cos(p)+ Ga1.*h.*r.*v0.*cos(p).^2+ 2.* ...
  dp.^2.*h.^(-1).*mu.*r.*v0.*cos(p).^2+ 2.*dp.^2.*h.^(-1).*mub.*r.* ...
  v0.*cos(p).^2+ 2.*dp.*mub.*vu.*cos(p).^2+ h.*la.*cos(p).*sin(p)+ h.* ...
  sig.^2.*(sig.^2+ Sig0.^2).^(-1).*xi.*cos(p).*sin(p)+ dvu.*mub.*sin( ...
  2.*p)+ 2.*dp.*mub.*v0.*cos(p).*sin(2.*p)+ h.*mu.*r.^(-1).*vu.*cos(p) ...
  .*sin(2.*p)+ h.*mub.*r.^(-1).*vu.*cos(p).*sin(2.*p)+ h.*mu.*r.^(-1) ...
  .*v0.*cos(p).*sin(p).*sin(2.*p)+ h.*mub.*r.^(-1).*v0.*cos(p).*sin( ...
  p).*sin(2.*p);

dy(7,:)=dvu;

dy(8,:)=(-1/2).*fu.*h.^2.*(mu+ mub).^(-1)+ (-1/2).*dp.*h.*mu.*(mu+ mub).^( ...
  -1).*r.^(-1).*v0+ (1/2).*Ga2.*h.^2.*(mu+ mub).^(-1).*vu+ (-1).*dsig.* ...
  h.*(mu+ mub).^(-1).*sig.*Sig0.^2.*(sig.^2+ Sig0.^2).^(-2).*xi+ (-1).* ...
  dvu.*h.*mu.*(mu+ mub).^(-1).*r.^(-1).*cos(p)+ (-1).*dvu.*h.*mub.*( ...
  mu+ mub).^(-1).*r.^(-1).*cos(p)+ dka.*dp.*ka.^(-1).*mu.*(mu+ mub).^( ...
  -1).*v0.*cos(p)+ (-1).*c0.*dka.*h.*ka.^(-1).*mu.*(mu+ mub).^(-1).* ...
  v0.*cos(p)+ dka.*dp.*ka.^(-1).*mub.*(mu+ mub).^(-1).*v0.*cos(p)+ (-1) ...
  .*c0.*dka.*h.*ka.^(-1).*mub.*(mu+ mub).^(-1).*v0.*cos(p)+ dp.*h.* ...
  mu.*(mu+ mub).^(-1).*r.^(-1).*v0.*cos(p).^2+ (-1).*be.*h.^2.*ka.^( ...
  -1).*mu.*(mu+ mub).^(-1).*r.^(-1).*v0.*cos(p).^2+ dp.*h.*mub.*(mu+  ...
  mub).^(-1).*r.^(-1).*v0.*cos(p).^2+ (-1).*be.*h.^2.*ka.^(-1).*mub.* ...
  (mu+ mub).^(-1).*r.^(-1).*v0.*cos(p).^2+ h.^2.*mu.*(mu+ mub).^(-1).* ...
  r.^(-2).*vu.*cos(p).^2+ h.^2.*mub.*(mu+ mub).^(-1).*r.^(-2).*vu.* ...
  cos(p).^2+ (-1/2).*dp.*h.*mu.*(mu+ mub).^(-1).*r.^(-1).*v0.*cos(2.* ...
  p)+ (-1).*dp.*h.*mub.*(mu+ mub).^(-1).*r.^(-1).*v0.*cos(2.*p)+  ...
  dp.^2.*mu.*(mu+ mub).^(-1).*v0.*sin(p)+ dp.^2.*mub.*(mu+ mub).^(-1).* ...
  v0.*sin(p)+ dp.*h.*mub.*(mu+ mub).^(-1).*r.^(-1).*vu.*sin(p)+ dka.* ...
  h.*ka.^(-1).*mu.*(mu+ mub).^(-1).*r.^(-1).*v0.*cos(p).*sin(p)+ (-1) ...
  .*al.*h.^2.*ka.^(-1).*mu.*(mu+ mub).^(-1).*r.^(-1).*v0.*cos(p).* ...
  sin(p)+ dka.*h.*ka.^(-1).*mub.*(mu+ mub).^(-1).*r.^(-1).*v0.*cos(p) ...
  .*sin(p)+ (-1).*al.*h.^2.*ka.^(-1).*mub.*(mu+ mub).^(-1).*r.^(-1).* ...
  v0.*cos(p).*sin(p);

dy(9,:)=dsig;

dy(10,:)=Di.^(-1).*dvu.*h.*sig+ Di.^(-1).*h.^2.*ksig.*sig+ (-1).*Di.^(-1).* ...
  h.^2.*ksig.*sigeq+ Di.^(-1).*dsig.*h.*vu+ (-1).*dsig.*h.*r.^(-1).* ...
  cos(p)+ Di.^(-1).*dp.*h.*sig.*v0.*cos(p)+ Di.^(-1).*h.^2.*r.^(-1).* ...
  sig.*vu.*cos(p)+ Di.^(-1).*dsig.*h.*v0.*sin(p)+ Di.^(-1).*h.^2.*r.^( ...
  -1).*sig.*v0.*cos(p).*sin(p);

dy(11,:)=(1/2).*h.*r.^2.*sin(p);

dy(12,:)=0;


